global:
  scrape_interval: 1m
  evaluation_interval: 1m
  scrape_timeout: 30s


rule_files:
  - '/etc/prometheus/alert_rules.yml'
  - '/etc/prometheus/recording_rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(node_network_.*|node_load.*|node_time_seconds|node_filesystem_inodes_.*|node_memory_.*|node_cpu_.*|node_filesystem_.*|node_disk_.*)'
        action: keep
